name: run-checks

permissions: read-all

on:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-latest, macos-latest, windows-latest]
        # https://github.com/nodejs/Release#release-schedule
        node: [22, 24, 26]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.0.0
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: Disable AppArmor
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Run code checks
        run: |
          npm run lint

      - name: Run tests
        run: npm run test

  headful-checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [24]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.0.0
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: Disable AppArmor
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Install dependencies
        run: |
          sudo apt-get install xvfb
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Run tests in headful
        run: xvfb-run --auto-servernum npm run test:headful
